# Generated by Django 2.1.1 on 2018-09-06 03:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_n', models.DateField(blank=True, null=True)),
                ('fecha_d', models.DateField(blank=True, null=True, verbose_name='Muerto')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para este libro particular en toda la biblioteca', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('fecha_en', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('m', 'Mantenimiento'), ('o', 'En prestamo'), ('a', 'Disponible'), ('r', 'Reservado')], default='m', help_text='Estado de disponibilidad del libro', max_length=1)),
            ],
            options={
                'ordering': ['fecha_en'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese un género para el libro', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Autor')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this book', to='catalog.Genero')),
            ],
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Libro'),
        ),
    ]
