# Generated by Django 2.1.1 on 2018-09-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180906_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leng', models.CharField(blank=True, choices=[('esp', 'Español'), ('eng', 'English'), ('esp', 'Esperanto')], default='esp', help_text='Lenguaje del libro', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='lenguaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Lenguaje'),
        ),
    ]
