# Generated by Django 2.1.1 on 2018-09-12 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_auto_20180911_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='leng',
            field=models.CharField(blank=True, choices=[('esp', 'Español'), ('eng', 'English'), ('esp', 'Esperanto')], default='esp', help_text='Lenguaje del libro', max_length=15),
        ),
    ]
