# Generated by Django 2.1.1 on 2018-09-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180912_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancia',
            options={'ordering': ['fecha_en'], 'permissions': (('puede_marcar_retornado', 'Setea la instancia como devuelta'),)},
        ),
    ]
